#!/usr/bin/env python3
"""Author the content files that Web V1 had no equivalent of.

Everything here is new material, not extracted: the Italian pronunciation
warm-up, the Italy scenario set, idioms, culture cards and language tips.
Written as a script so the JSON stays consistent in shape and can be
regenerated after an edit rather than hand-patched.
"""
import json
import os

OUT = "/Users/ez__rekt/Desktop/SpasiBoh/ios/SpasiBohCore/Sources/SpasiBohCore/Resources/Content"


def side(text, pron=None, stressed=None, audio=None, rank=9999, example=None):
    return {
        "text": text,
        "stressed": stressed,
        "pronunciation": pron,
        "audioText": audio or text,
        "frequencyRank": rank,
        "example": example,
    }


def note(it, ru):
    return {"it": it, "ru": ru}


# ---------------------------------------------------------------- patterns
# The Russian-speaking learner already reads Latin script. The real difficulty
# is Italian orthography: digraphs that do not exist in Russian, consonant
# length that carries meaning, and stress that is not marked in writing.
# `pronunciation` is written for a Russian ear, which is what this field is for.

def pattern(id, kind, pat, pron, key, word, translated, confusable=None,
            minimal=None, note_=None, order=0):
    return {
        "id": id, "kind": kind, "pattern": pat, "pronunciation": pron,
        "soundKey": key, "exampleWord": word, "exampleWordTranslated": translated,
        "confusableWith": confusable or [], "minimalPair": minimal,
        "note": note_, "order": order,
    }


def pair(short, short_it, short_ru, long, long_it, long_ru):
    return {
        "short": short, "shortMeaning": note(short_it, short_ru),
        "long": long, "longMeaning": note(long_it, long_ru),
    }


PATTERNS = [
    pattern("gli", "digraph", "gli", "ль (мягкое, как в «Илья»)", "ль",
            "famiglia", "семья", ["li", "gn"],
            note_=note("GLI non è G + L + I: è un suono solo, palatale.",
                       "GLI — это не Г+Л+И, а один мягкий звук, близкий к «ль» в «Илья»."),
            order=1),
    pattern("gn", "digraph", "gn", "нь (как в «конь»)", "нь",
            "signore", "господин", ["gli", "ni"],
            note_=note("GN è una sola consonante nasale palatale.",
                       "GN — один звук, мягкое «нь». Не «гн»."),
            order=2),
    pattern("sc_soft", "digraph", "sci / sce", "ш", "ш",
            "sciare", "кататься на лыжах", ["sc_hard", "s"],
            note_=note("SC davanti a I ed E suona come «sh».",
                       "SC перед I и E читается как «ш»: sciare — «шьяре»."),
            order=3),
    pattern("sc_hard", "digraph", "sca / sco / scu / sch", "ск", "ск",
            "scuola", "школа", ["sc_soft"],
            note_=note("SC davanti ad A, O, U resta dura.",
                       "SC перед A, O, U читается «ск»: scuola — «скуола»."),
            order=4),
    pattern("c_soft", "digraph", "ci / ce", "ч", "ч",
            "ciao", "привет", ["c_hard", "ch"],
            note_=note("C davanti a I ed E suona «ch».",
                       "C перед I и E читается «ч»: ciao — «чао»."),
            order=5),
    pattern("c_hard", "digraph", "ca / co / cu", "к", "к",
            "casa", "дом", ["c_soft"],
            note_=note("C davanti ad A, O, U suona «k».",
                       "C перед A, O, U читается «к»: casa — «каза»."),
            order=6),
    pattern("ch", "digraph", "chi / che", "к", "к",
            "chiave", "ключ", ["c_soft"],
            note_=note("La H serve solo a mantenere il suono duro.",
                       "H здесь немая: она только сохраняет твёрдое «к». chiave — «кьяве»."),
            order=7),
    pattern("g_soft", "digraph", "gi / ge", "дж", "дж",
            "gelato", "мороженое", ["g_hard", "gh"],
            note_=note("G davanti a I ed E suona «dj».",
                       "G перед I и E читается «дж»: gelato — «джелато»."),
            order=8),
    pattern("g_hard", "digraph", "ga / go / gu", "г", "г",
            "gatto", "кот", ["g_soft"],
            note_=note("G davanti ad A, O, U resta dura.",
                       "G перед A, O, U читается «г»: gatto — «гатто»."),
            order=9),
    pattern("gh", "digraph", "ghi / ghe", "г", "г",
            "spaghetti", "спагетти", ["g_soft"],
            note_=note("Come per CH, la H mantiene il suono duro.",
                       "Как и в CH, H сохраняет твёрдое «г»: spaghetti — «спагетти»."),
            order=10),
    pattern("qu", "digraph", "qu", "ку (кв)", "ку",
            "quattro", "четыре", ["c_hard"],
            note_=note("QU si legge sempre «ku», mai «kv» pieno.",
                       "QU всегда «ку» с очень коротким «у»: quattro — «куаттро»."),
            order=11),
    pattern("z_voiceless", "vowelOrZ", "z (sorda)", "ц", "ц",
            "pizza", "пицца", ["z_voiced"],
            note_=note("La Z sorda suona «ts».",
                       "Глухая Z читается «ц»: pizza — «пицца»."),
            order=12),
    pattern("z_voiced", "vowelOrZ", "z (sonora)", "дз", "дз",
            "zero", "ноль", ["z_voiceless"],
            note_=note("La Z sonora suona «dz». Non c'è una regola sicura: si impara parola per parola.",
                       "Звонкая Z читается «дз»: zero — «дзеро». Надёжного правила нет — запоминается со словом."),
            order=13),
    pattern("open_closed_e", "vowelOrZ", "è / é", "открытое и закрытое «э»", "э",
            "pèsca / pésca", "персик / рыбалка", ["z_voiced"],
            note_=note("La E aperta e chiusa distingue alcune parole scritte uguali.",
                       "Открытое и закрытое «э» различают слова, которые пишутся одинаково: pèsca (персик) и pésca (рыбалка)."),
            order=14),
    pattern("double_ll", "doubleConsonant", "pala / palla", "долгая согласная", "лл",
            "palla", "мяч", ["double_tt"],
            minimal=pair("pala", "pala — badile", "лопата",
                         "palla", "palla — sfera da gioco", "мяч"),
            note_=note("La consonante doppia va tenuta più a lungo: cambia la parola.",
                       "Двойная согласная тянется дольше — и это меняет слово."),
            order=15),
    pattern("double_tt", "doubleConsonant", "sete / sette", "долгая согласная", "тт",
            "sette", "семь", ["double_ll"],
            minimal=pair("sete", "sete — bisogno di bere", "жажда",
                         "sette", "sette — il numero 7", "семь"),
            note_=note("«Ho sete» e «ho sette» non sono la stessa cosa.",
                       "«Ho sete» (хочу пить) и «sette» (семь) — разные слова."),
            order=16),
    pattern("double_ss", "doubleConsonant", "casa / cassa", "долгая согласная", "сс",
            "cassa", "касса", ["double_nn"],
            minimal=pair("casa", "casa — abitazione", "дом",
                         "cassa", "cassa — dove si paga", "касса"),
            note_=note("Anche la S singola fra vocali si sonorizza: «casa» suona «kaza».",
                       "Одиночная S между гласными звучит звонко: casa — «каза», а cassa — «касса»."),
            order=17),
    pattern("double_nn", "doubleConsonant", "nono / nonno", "долгая согласная", "нн",
            "nonno", "дедушка", ["double_ss"],
            minimal=pair("nono", "nono — il numero 9 ordinale", "девятый",
                         "nonno", "nonno — il padre del padre", "дедушка"),
            order=18),
    pattern("stress_penult", "stress", "stress по умолчанию", "ударение на предпоследнем слоге", "—",
            "amìco", "друг", ["stress_irregular"],
            note_=note("La maggior parte delle parole ha l'accento sulla penultima sillaba.",
                       "У большинства слов ударение на предпоследнем слоге — и оно не пишется."),
            order=19),
    pattern("stress_irregular", "stress", "àbito, tèlefono", "ударение на третьем слоге с конца", "—",
            "tèlefono", "телефон", ["stress_penult"],
            note_=note("Molte parole comuni sono sdrucciole: l'accento cade sulla terzultima.",
                       "Многие частые слова имеют ударение на третьем слоге с конца: tèlefono, àbito, mèdico."),
            order=20),
    pattern("stress_final", "stress", "città, perché", "ударение на последнем слоге (пишется)", "—",
            "città", "город", ["stress_irregular"],
            note_=note("Quando l'accento cade sull'ultima vocale, si scrive.",
                       "Если ударение на последнем гласном, оно пишется: città, perché, caffè."),
            order=21),
]

# ---------------------------------------------------------------- idioms

def idiom(id, lang, expr, pron, lit_it, lit_ru, mean_it, mean_ru, equiv,
          register, use_it, use_ru, culture=None):
    return {
        "id": id, "language": lang, "expression": expr, "pronunciation": pron,
        "literal": note(lit_it, lit_ru), "meaning": note(mean_it, mean_ru),
        "equivalent": equiv, "register": register,
        "usage": note(use_it, use_ru), "culturalNote": culture,
    }


IDIOMS = [
    idiom("it_boh", "it", "boh", "бо",
          "boh", "«бо»",
          "Non lo so, e non ho intenzione di indagare.", "«Не знаю» — и выяснять не собираюсь.",
          "не знаю", "colloquial",
          "Risposta completa a una domanda. Da solo, senza altro.",
          "Полноценный ответ на вопрос. Говорится отдельно, без продолжения.",
          note("Dà il nome a questa app: «spasibo» + «boh».",
               "Именно от него название приложения: «спасибо» + «boh».")),
    idiom("it_magari", "it", "magari", "магари",
          "magari", "«магари»",
          "Se solo fosse vero — oppure «forse», secondo il tono.",
          "«Хорошо бы!» — или «может быть», в зависимости от интонации.",
          "хоть бы", "neutral",
          "Da solo esprime un desiderio; in una frase significa «forse».",
          "Отдельно — сильное желание; внутри фразы — «может быть»."),
    idiom("it_figurati", "it", "figurati", "фигурати",
          "figurati", "«представь себе»",
          "Ma no, non c'è di che.", "«Да брось, не за что».",
          "не за что", "informal",
          "Risposta a un grazie o a una scusa.",
          "Ответ на «спасибо» или на извинение."),
    idiom("it_in_bocca_al_lupo", "it", "in bocca al lupo", "ин бокка ал лупо",
          "in bocca al lupo", "«в пасть волку»",
          "Buona fortuna.", "«Удачи!»",
          "ни пуха ни пера", "neutral",
          "Si risponde «crepi» — non «grazie».",
          "Отвечают «crepi!», а не «grazie»."),
    idiom("it_non_vedo_ora", "it", "non vedo l'ora", "нон ведо лора",
          "non vedo l'ora", "«не вижу часа»",
          "Non sto nella pelle dall'attesa.", "«Жду не дождусь».",
          "жду не дождусь", "neutral",
          "Seguito da «di» + infinito.", "Дальше идёт «di» + инфинитив."),
    idiom("it_che_palle", "it", "che palle", "ке палле",
          "che palle", "«какие шары»",
          "Che noia insopportabile.", "«Какая тоска».",
          "какая скука", "vulgar",
          "Volgare. Fra amici passa, altrove no.",
          "Грубовато. Между друзьями нормально, в остальных случаях — нет."),
    idiom("ru_davai", "ru", "давай", "davàj",
          "dai / andiamo", "«дай»",
          "Ok, ci sentiamo — è anche un modo di chiudere una telefonata.",
          "«Ну ладно, пока» — в том числе как способ закончить разговор.",
          "dai", "informal",
          "Serve a proporre, a incitare e a salutare. Il tono decide.",
          "Служит и предложением, и подбадриванием, и прощанием. Решает интонация."),
    idiom("ru_nu", "ru", "ну", "nu",
          "beh", "«ну»",
          "Riempitivo che chiede all'altro di andare avanti.",
          "Слово-заполнитель: просит собеседника продолжать.",
          "beh", "colloquial",
          "Onnipresente nel parlato, quasi assente nello scritto.",
          "Постоянно в устной речи, почти не встречается в письменной."),
    idiom("ru_kak_raz", "ru", "как раз", "kak ràz",
          "proprio come", "«как раз»",
          "Esattamente, proprio quello che serviva.",
          "«Именно то, что нужно».",
          "proprio", "neutral",
          "Spesso all'inizio della frase.", "Часто в начале фразы."),
    idiom("ru_ni_puha", "ru", "ни пуха ни пера", "ni pùha ni perà",
          "né piuma né penna", "«ни пуха ни пера»",
          "In bocca al lupo.", "Пожелание удачи.",
          "in bocca al lupo", "informal",
          "Si risponde «к чёрту!» — «al diavolo».",
          "Отвечают «к чёрту!»",
          note("Formula di caccia: augurare bene portava sfortuna, quindi si augurava male.",
               "Охотничья формула: прямое пожелание удачи считалось дурной приметой.")),
    idiom("ru_normalno", "ru", "нормально", "narmàl'na",
          "normalmente", "«нормально»",
          "Bene, tutto a posto — non «così così».",
          "«Хорошо», а не «так себе».",
          "bene", "neutral",
          "Risposta standard a «come va?». Non è tiepida come sembra a un italiano.",
          "Обычный ответ на «как дела?». Это не вялое «так себе»."),
    idiom("ru_tak_i_byt", "ru", "так и быть", "tak i byt'",
          "così sia", "«так и быть»",
          "E va bene, te lo concedo.", "«Ладно уж, так и быть».",
          "e va bene", "informal",
          "Concessione, spesso scherzosa.", "Уступка, часто в шутку."),
]

# ---------------------------------------------------------------- culture
# Every card states where the fact comes from. Nothing invented.

def card(id, audience, title_it, title_ru, body_it, body_ru, symbol, source, xp):
    return {
        "id": id, "audience": audience,
        "title": note(title_it, title_ru), "body": note(body_it, body_ru),
        "symbolName": symbol, "source": source, "unlockXP": xp,
    }


CULTURE = [
    card("ru_patronymic", "it-ru",
         "Il patronimico", "Отчество",
         "Un nome russo completo ha tre parti: nome, patronimico (dal nome del padre) e cognome. "
         "Rivolgersi a qualcuno con nome + patronimico — «Ivan Petrovič» — è la forma rispettosa "
         "normale al lavoro e con le persone più anziane.",
         "Полное русское имя состоит из трёх частей: имя, отчество и фамилия. Обращение по имени и "
         "отчеству — вежливая норма на работе и со старшими.",
         "person.text.rectangle",
         "Encyclopaedia Britannica, «Russian name»; Wikipedia, «Eastern Slavic naming customs»", 0),
    card("ru_shoes", "it-ru",
         "Le scarpe si tolgono", "Обувь снимают",
         "Entrando in una casa russa ci si toglie le scarpe. Spesso l'ospite offre delle pantofole. "
         "Non è una richiesta particolare: è semplicemente quello che si fa.",
         "Входя в дом, в России снимают обувь. Хозяева обычно предлагают тапочки.",
         "shoe", "Wikipedia, «Russian traditions and superstitions»", 50),
    card("ru_flowers", "it-ru",
         "Fiori: sempre in numero dispari", "Цветы — нечётное число",
         "I mazzi di fiori si regalano in numero dispari. Il numero pari è riservato ai funerali. "
         "È una convenzione presa sul serio: contare i fiori prima di regalarli è normale.",
         "Букеты дарят из нечётного числа цветов. Чётное число несут на похороны.",
         "leaf", "Wikipedia, «Russian traditions and superstitions»", 100),
    card("ru_tolyatti", "it-ru",
         "Togliatti, città russa", "Тольятти",
         "Sul Volga c'è una città di oltre 600.000 abitanti che si chiama Togliatti, dal nome del "
         "segretario del Partito Comunista Italiano Palmiro Togliatti, morto in URSS nel 1964. "
         "Ci si costruiscono le Lada, nate da un accordo con la FIAT.",
         "На Волге есть город с населением более 600 тысяч человек — Тольятти, названный в честь "
         "лидера Итальянской компартии Пальмиро Тольятти. Там выпускают «Жигули», созданные по "
         "соглашению с FIAT.",
         "car", "Encyclopaedia Britannica, «Tolyatti»; Wikipedia, «AvtoVAZ»", 150),
    card("ru_tea", "it-ru",
         "Il tè non finisce mai", "Чай не заканчивается",
         "Il tè si beve tutto il giorno e si accompagna a qualcosa di dolce. Rifiutare del tutto "
         "l'offerta può sembrare freddo: accettarne anche solo una tazza è il gesto giusto.",
         "Чай пьют весь день и обязательно с чем-то сладким. Полный отказ может показаться холодным.",
         "cup.and.saucer", "Wikipedia, «Russian tea culture»", 200),
    card("ru_ty_vy", "it-ru",
         "Ты e вы", "«Ты» и «вы»",
         "Come in italiano, il russo distingue il «tu» dal «lei»: ты con amici e coetanei, вы con "
         "sconosciuti, al lavoro e con persone più anziane. Il passaggio a ты si propone, non si "
         "dà per scontato.",
         "Как и в итальянском, есть «ты» и «вы». Переход на «ты» предлагают, а не подразумевают.",
         "person.2", "Wikipedia, «T–V distinction»", 250),
    card("it_bar_coffee", "ru-it",
         "Il caffè si beve in piedi", "Кофе пьют стоя",
         "Al bar italiano si ordina alla cassa, si beve in piedi al banco e si esce. Sedersi al "
         "tavolino spesso costa di più: è il servizio, non il caffè.",
         "В итальянском баре заказывают у кассы, пьют стоя у стойки и уходят. За столиком часто "
         "дороже — платят за обслуживание, а не за кофе.",
         "cup.and.saucer", "Wikipedia, «Italian coffee culture»; Codice del Consumo, listino prezzi al banco/tavolo", 0),
    card("it_cappuccino", "ru-it",
         "Il cappuccino è del mattino", "Капучино — только утром",
         "Il cappuccino si beve a colazione. Dopo pranzo gli italiani prendono un caffè — cioè un "
         "espresso. Nessuno vieta niente, ma ordinarlo alle tre del pomeriggio si nota.",
         "Капучино пьют на завтрак. После обеда берут «caffè» — то есть эспрессо.",
         "mug", "Wikipedia, «Cappuccino»", 50),
    card("it_scontrino", "ru-it",
         "Lo scontrino", "Чек",
         "Lo scontrino fiscale va conservato uscendo dal locale. È un obbligo di legge, e nei bar "
         "si paga alla cassa prima di ordinare al banco.",
         "Кассовый чек нужно сохранять при выходе. Это требование закона, а в барах сначала платят "
         "в кассу и только потом заказывают у стойки.",
         "receipt", "Agenzia delle Entrate, documento commerciale (scontrino fiscale)", 100),
    card("it_convalida", "ru-it",
         "Convalidare il biglietto", "Компостировать билет",
         "Sui treni regionali e sugli autobus il biglietto cartaceo va convalidato prima di salire, "
         "nella macchinetta gialla o verde. Un biglietto valido ma non convalidato prende comunque "
         "la multa.",
         "На региональных поездах и автобусах бумажный билет нужно прокомпостировать до посадки. "
         "Действительный, но непрокомпостированный билет — всё равно штраф.",
         "ticket", "Trenitalia, condizioni di trasporto regionale", 150),
    card("it_aperitivo", "ru-it",
         "L'aperitivo", "Аперитиво",
         "Fra le 18 e le 21 si beve qualcosa e con il bicchiere arriva da mangiare, spesso incluso "
         "nel prezzo. Non è la cena, anche se in alcune città ci somiglia molto.",
         "Между 18 и 21 берут напиток, и к нему приносят закуски — часто включённые в цену. "
         "Это не ужин, хотя в некоторых городах очень похоже.",
         "wineglass", "Wikipedia, «Aperitivo»", 200),
    card("it_regions", "ru-it",
         "L'Italia parla molte lingue", "Италия говорит на многих языках",
         "Accanto all'italiano esistono lingue regionali vive — napoletano, siciliano, sardo, "
         "friulano — non semplici accenti. Alcune hanno tutela ufficiale.",
         "Кроме итальянского в стране живут региональные языки — неаполитанский, сицилийский, "
         "сардинский, фриульский. Это не просто акценты; некоторые имеют официальную защиту.",
         "map", "UNESCO Atlas of the World's Languages in Danger; Legge 482/1999", 250),
]

# ---------------------------------------------------------------- tips

def tip(id, lang, title_it, title_ru, body_it, body_ru, ex_it=None, ex_ru=None, xp=0):
    return {
        "id": id, "language": lang,
        "title": note(title_it, title_ru), "body": note(body_it, body_ru),
        "example": note(ex_it, ex_ru) if ex_it else None,
        "unlockXP": xp,
    }


TIPS = [
    tip("ru_no_articles", "ru",
        "Il russo non ha articoli", "В русском нет артиклей",
        "Non esistono «il», «la», «un». Non si traducono: si tolgono e basta.",
        "Артиклей нет вовсе. Их не переводят — их просто нет.",
        "«Il libro è sul tavolo» → «Книга на столе».",
        "«Il libro è sul tavolo» → «Книга на столе».", 0),
    tip("ru_no_present_be", "ru",
        "«Essere» sparisce al presente", "Глагол «быть» в настоящем не нужен",
        "Al presente il verbo essere non si scrive. «Io sono italiano» diventa «Я итальянец».",
        "В настоящем времени глагол «быть» опускается.",
        "«Sono a casa» → «Я дома».", "«Sono a casa» → «Я дома».", 30),
    tip("ru_stress", "ru",
        "L'accento cambia tutto", "Ударение решает всё",
        "L'accento russo è imprevedibile, non si scrive, e sposta il suono delle vocali. "
        "Va imparato insieme alla parola, non dopo.",
        "Ударение непредсказуемо и не пишется, но меняет звучание гласных.",
        "за́мок (castello) / замо́к (serratura)",
        "за́мок (castello) / замо́к (serratura)", 60),
    tip("ru_cases", "ru",
        "Sei casi", "Шесть падежей",
        "La funzione della parola nella frase si vede dalla desinenza, non dall'ordine. "
        "Per questo l'ordine delle parole è molto più libero che in italiano.",
        "Роль слова в предложении показывает окончание, а не порядок слов.",
        "«Вижу маму» — la desinenza dice chi vede chi.",
        "«Вижу маму» — окончание показывает, кто кого видит.", 120),
    tip("ru_verbs_aspect", "ru",
        "Ogni verbo viene in coppia", "Глаголы ходят парами",
        "I verbi russi hanno due forme: una per l'azione in corso o ripetuta, una per l'azione "
        "portata a termine. Non è il nostro passato prossimo contro imperfetto, ma ci somiglia.",
        "У глагола две формы: несовершенная и совершенная.",
        "читать (leggere) / прочитать (finire di leggere)",
        "читать / прочитать", 200),
    tip("ru_yo", "ru",
        "La ё che non si scrive", "Буква ё, которую не пишут",
        "Nei testi normali la ё è quasi sempre scritta е. Si legge comunque «jo» ed è sempre accentata.",
        "В обычных текстах ё почти всегда пишут как е, но читается она «йо» и всегда под ударением.",
        "ещё si trova scritto «еще».", "«ещё» часто пишут «еще».", 260),
    tip("ru_polite", "ru",
        "Пожалуйста fa due lavori", "«Пожалуйста» работает дважды",
        "Vuol dire «per favore» e anche «prego» come risposta a «grazie».",
        "Это и «пожалуйста» при просьбе, и ответ на «спасибо».", None, None, 320),
    tip("it_gender", "it",
        "Tutto ha un genere", "У всего есть род",
        "Ogni sostantivo è maschile o femminile, e articolo e aggettivo si accordano. "
        "Non c'è il neutro del russo.",
        "Каждое существительное мужского или женского рода; артикль и прилагательное согласуются. "
        "Среднего рода, как в русском, нет.",
        "il libro rosso / la casa rossa", "il libro rosso / la casa rossa", 0),
    tip("it_articles", "it",
        "Gli articoli", "Артикли",
        "L'italiano ha articoli determinativi e indeterminativi, e la forma cambia con la lettera "
        "che segue: il, lo, l', la, i, gli, le. Non esistono in russo, quindi vanno imparati a memoria.",
        "В итальянском есть определённые и неопределённые артикли, и форма зависит от следующего "
        "звука. В русском их нет, поэтому запоминать приходится отдельно.",
        "lo studente, l'amico, gli zaini", "lo studente, l'amico, gli zaini", 30),
    tip("it_double_consonants", "it",
        "Le doppie si sentono", "Двойные согласные слышны",
        "La consonante doppia si tiene più a lungo e distingue parole diverse. "
        "Pronunciarla come singola cambia quello che hai detto.",
        "Двойная согласная тянется дольше и различает слова.",
        "nono (nono) / nonno (nonno)", "nono (девятый) / nonno (дедушка)", 60),
    tip("it_stress_written", "it",
        "L'accento scritto", "Письменное ударение",
        "L'accento si scrive solo quando cade sull'ultima vocale. Negli altri casi va saputo.",
        "Ударение пишется, только если падает на последний гласный. В остальных случаях его надо знать.",
        "città, perché, però", "città, perché, però", 120),
    tip("it_verbs", "it",
        "Il verbo dice già chi", "Глагол уже называет лицо",
        "La desinenza indica la persona, quindi il pronome soggetto di solito si omette.",
        "Окончание показывает лицо, поэтому местоимение обычно опускают.",
        "«Parlo italiano», non «Io parlo italiano».",
        "«Parlo italiano», а не «Io parlo italiano».", 200),
    tip("it_lei", "it",
        "Il «lei» di cortesia", "Вежливое «Lei»",
        "La forma di cortesia usa la terza persona femminile singolare, anche parlando a un uomo.",
        "Вежливая форма — третье лицо женского рода единственного числа, даже если собеседник мужчина.",
        "«Lei come si chiama?»", "«Lei come si chiama?»", 260),
    tip("it_false_friends", "it",
        "Falsi amici", "Ложные друзья",
        "Alcune parole somigliano al russo ma non significano lo stesso.",
        "Некоторые слова похожи на русские, но значат другое.",
        "«famiglia» non è «фамилия» (cognome): è «семья».",
        "«famiglia» — это «семья», а не «фамилия».", 320),
]

# ---------------------------------------------------------------- scenarios
# Italy set, written around what actually happens in Italy — not translations
# of the Moscow scenarios.

def step(id, kind, npc_it=None, npc_ru=None, prompt_it="", prompt_ru="",
         target_it=None, target_ru=None, distractors=None,
         options_it=None, options_ru=None, correct=None, hint=None):
    return {
        "id": id, "kind": kind,
        "npcIt": npc_it, "npcRu": npc_ru,
        "prompt": note(prompt_it, prompt_ru),
        "targetIt": target_it, "targetRu": target_ru,
        "distractors": distractors or {},
        "optionsIt": options_it or [], "optionsRu": options_ru or [],
        "correctOption": correct, "hint": hint,
    }


def scenario(id, title_it, title_ru, symbol, intro_it, intro_ru, category, difficulty, steps):
    return {
        "id": id, "direction": "ru-it",
        "title": note(title_it, title_ru), "symbolName": symbol,
        "intro": note(intro_it, intro_ru),
        "category": category, "difficulty": difficulty, "steps": steps,
    }


ITALY = [
    scenario("it-bar-caffe", "Al bar", "В баре", "cup.and.saucer",
             "Un caffè al banco, come si fa davvero.",
             "Кофе у стойки — так, как это делают на самом деле.",
             "bar", 1, [
        step("bar-1", "info", prompt_ru="Сначала платят в кассе, потом заказывают у стойки.",
             prompt_it="Prima si paga alla cassa, poi si ordina al banco."),
        step("bar-2", "comprehension",
             npc_it=side("Buongiorno! Mi dica.", pron="буонджорно! ми дика"),
             npc_ru=side("Здравствуйте! Слушаю вас."),
             prompt_ru="Что сказал бариста?", prompt_it="Che cosa ha detto il barista?",
             options_ru=["Здравствуйте! Слушаю вас.", "Мы закрыты.",
                         "Заплатите потом.", "Столик на двоих?"],
             correct=0),
        step("bar-3", "build",
             prompt_ru="Скажи: «Один эспрессо, пожалуйста».",
             prompt_it="Ordina un caffè.",
             target_it=side("Un caffè, per favore.", pron="ун каффè, пер фаворе"),
             target_ru=side("Один кофе, пожалуйста."),
             distractors={"it": ["grazie", "dove"]}),
        step("bar-4", "choice",
             npc_it=side("Al banco o al tavolo?"),
             npc_ru=side("У стойки или за столиком?"),
             prompt_ru="За столиком дороже. Выбери ответ.",
             prompt_it="Al tavolo si paga di più. Scegli.",
             options_it=["Al banco, grazie.", "Al tavolo, grazie.",
                         "Non lo so.", "Da portare via."],
             correct=0,
             hint=note("Al banco è la scelta normale e costa meno.",
                       "У стойки — обычный выбор и дешевле.")),
        step("bar-5", "pronounce",
             prompt_ru="Произнеси вслух.", prompt_it="Dillo ad alta voce.",
             target_it=side("Quanto viene?", pron="куанто вьене"),
             target_ru=side("Сколько с меня?")),
        step("bar-6", "comprehension",
             npc_it=side("Un euro e dieci. Ecco lo scontrino."),
             npc_ru=side("Один евро десять. Вот чек."),
             prompt_ru="Что он тебе дал?", prompt_it="Che cosa ti ha dato?",
             options_ru=["Чек", "Сдачу монетами", "Меню", "Ключ"],
             correct=0),
        step("bar-7", "build",
             prompt_ru="Поблагодари и попрощайся.",
             prompt_it="Ringrazia e saluta.",
             target_it=side("Grazie, arrivederci."),
             target_ru=side("Спасибо, до свидания."),
             distractors={"it": ["scusi"]}),
    ]),

    scenario("it-treno-regionale", "Il treno regionale", "Региональный поезд", "tram",
             "Comprare il biglietto e convalidarlo prima di salire.",
             "Купить билет и прокомпостировать его до посадки.",
             "train", 2, [
        step("tr-1", "build",
             prompt_ru="Попроси билет до Флоренции.",
             prompt_it="Chiedi un biglietto per Firenze.",
             target_it=side("Un biglietto per Firenze, per favore."),
             target_ru=side("Один билет до Флоренции, пожалуйста."),
             distractors={"it": ["treno", "domani"]}),
        step("tr-2", "comprehension",
             npc_it=side("Solo andata o andata e ritorno?"),
             npc_ru=side("В одну сторону или туда и обратно?"),
             prompt_ru="О чём спрашивает кассир?",
             prompt_it="Che cosa ti chiede?",
             options_ru=["В одну сторону или туда-обратно?", "Первый или второй класс?",
                         "Наличными или картой?", "На какое число?"],
             correct=0),
        step("tr-3", "choice",
             prompt_ru="Тебе нужен билет в одну сторону.",
             prompt_it="Ti serve solo andata.",
             options_it=["Solo andata.", "Andata e ritorno.", "Prima classe.", "Domani."],
             correct=0),
        step("tr-4", "info",
             prompt_ru="Бумажный билет надо прокомпостировать в жёлтом или зелёном автомате.",
             prompt_it="Il biglietto cartaceo va convalidato nella macchinetta."),
        step("tr-5", "build",
             prompt_ru="Спроси, где прокомпостировать билет.",
             prompt_it="Chiedi dove convalidare.",
             target_it=side("Dove posso convalidare il biglietto?"),
             target_ru=side("Где можно прокомпостировать билет?"),
             distractors={"it": ["quando", "quanto"]}),
        step("tr-6", "comprehension",
             npc_it=side("Le macchinette gialle sono all'inizio del binario."),
             npc_ru=side("Жёлтые автоматы в начале платформы."),
             prompt_ru="Где автоматы?", prompt_it="Dove sono le macchinette?",
             options_ru=["В начале платформы", "В поезде", "У выхода", "В кассе"],
             correct=0),
        step("tr-7", "pronounce",
             prompt_ru="Произнеси вслух.", prompt_it="Dillo ad alta voce.",
             target_it=side("A che ora parte?"),
             target_ru=side("Во сколько отправление?")),
    ]),

    scenario("it-ristorante", "Al ristorante", "В ресторане", "menucard",
             "Ordinare, chiedere il conto e capire il coperto.",
             "Заказать, попросить счёт и понять, что такое coperto.",
             "restaurant", 2, [
        step("ri-1", "comprehension",
             npc_it=side("Buonasera, avete prenotato?"),
             npc_ru=side("Добрый вечер, вы бронировали?"),
             prompt_ru="О чём спрашивает официант?",
             prompt_it="Che cosa chiede il cameriere?",
             options_ru=["Бронировали ли вы столик", "Сколько вас", "Хотите ли вина", "Готовы ли заказать"],
             correct=0),
        step("ri-2", "build",
             prompt_ru="Скажи, что вас двое.", prompt_it="Dì che siete in due.",
             target_it=side("No, siamo in due."),
             target_ru=side("Нет, нас двое."),
             distractors={"it": ["tre", "grazie"]}),
        step("ri-3", "build",
             prompt_ru="Попроси меню.", prompt_it="Chiedi il menù.",
             target_it=side("Il menù, per favore."),
             target_ru=side("Меню, пожалуйста."),
             distractors={"it": ["conto"]}),
        step("ri-4", "choice",
             npc_it=side("Da bere?"),
             npc_ru=side("Что будете пить?"),
             prompt_ru="Попроси воду из-под крана.",
             prompt_it="Chiedi acqua del rubinetto.",
             options_it=["Acqua naturale, grazie.", "Un caffè, grazie.",
                         "Niente, grazie.", "Il conto, grazie."],
             correct=0),
        step("ri-5", "pronounce",
             prompt_ru="Произнеси вслух.", prompt_it="Dillo ad alta voce.",
             target_it=side("Che cosa mi consiglia?"),
             target_ru=side("Что вы посоветуете?")),
        step("ri-6", "info",
             prompt_ru="В счёте часто есть «coperto» — фиксированная плата за место и хлеб.",
             prompt_it="Nel conto c'è spesso il coperto."),
        step("ri-7", "build",
             prompt_ru="Попроси счёт.", prompt_it="Chiedi il conto.",
             target_it=side("Il conto, per favore."),
             target_ru=side("Счёт, пожалуйста."),
             distractors={"it": ["menù"]}),
    ]),

    scenario("it-supermercato", "Al supermercato", "В супермаркете", "cart",
             "Pesare la frutta e pagare alla cassa.",
             "Взвесить фрукты и заплатить на кассе.",
             "shopping", 2, [
        step("su-1", "info",
             prompt_ru="Фрукты и овощи взвешивают сами, в перчатках.",
             prompt_it="La frutta si pesa da soli, con i guanti."),
        step("su-2", "build",
             prompt_ru="Спроси, где весы.", prompt_it="Chiedi dov'è la bilancia.",
             target_it=side("Dov'è la bilancia?"),
             target_ru=side("Где весы?"),
             distractors={"it": ["cassa", "quanto"]}),
        step("su-3", "comprehension",
             npc_it=side("In fondo, vicino alla verdura."),
             npc_ru=side("В глубине зала, рядом с овощами."),
             prompt_ru="Где весы?", prompt_it="Dov'è la bilancia?",
             options_ru=["Рядом с овощами", "На кассе", "У входа", "На втором этаже"],
             correct=0),
        step("su-4", "choice",
             npc_it=side("Ha la carta fedeltà?"),
             npc_ru=side("У вас есть карта лояльности?"),
             prompt_ru="У тебя её нет.", prompt_it="Non ce l'hai.",
             options_it=["No, grazie.", "Sì, eccola.", "Non capisco.", "Con carta."],
             correct=0),
        step("su-5", "build",
             prompt_ru="Скажи, что заплатишь картой.",
             prompt_it="Dì che paghi con la carta.",
             target_it=side("Pago con la carta."),
             target_ru=side("Я заплачу картой."),
             distractors={"it": ["contanti"]}),
        step("su-6", "pronounce",
             prompt_ru="Произнеси вслух.", prompt_it="Dillo ad alta voce.",
             target_it=side("Mi serve un sacchetto."),
             target_ru=side("Мне нужен пакет.")),
    ]),

    scenario("it-farmacia", "In farmacia", "В аптеке", "cross.case",
             "Chiedere qualcosa senza ricetta.",
             "Попросить лекарство без рецепта.",
             "pharmacy", 3, [
        step("fa-1", "build",
             prompt_ru="Скажи, что у тебя болит голова.",
             prompt_it="Dì che hai mal di testa.",
             target_it=side("Ho mal di testa."),
             target_ru=side("У меня болит голова."),
             distractors={"it": ["stomaco", "gola"]}),
        step("fa-2", "comprehension",
             npc_it=side("Ha allergie a qualche farmaco?"),
             npc_ru=side("У вас есть аллергия на лекарства?"),
             prompt_ru="О чём спрашивает фармацевт?",
             prompt_it="Che cosa chiede il farmacista?",
             options_ru=["Об аллергии на лекарства", "О рецепте", "О возрасте", "О страховке"],
             correct=0),
        step("fa-3", "choice",
             prompt_ru="Аллергии у тебя нет.", prompt_it="Non hai allergie.",
             options_it=["No, nessuna.", "Sì, alla penicillina.",
                         "Non ho la ricetta.", "Quanto costa?"],
             correct=0),
        step("fa-4", "build",
             prompt_ru="Спроси, нужен ли рецепт.",
             prompt_it="Chiedi se serve la ricetta.",
             target_it=side("Serve la ricetta?"),
             target_ru=side("Нужен рецепт?"),
             distractors={"it": ["quanto"]}),
        step("fa-5", "pronounce",
             prompt_ru="Произнеси вслух.", prompt_it="Dillo ad alta voce.",
             target_it=side("Quante volte al giorno?"),
             target_ru=side("Сколько раз в день?")),
    ]),

    scenario("it-albergo", "In albergo", "В отеле", "bed.double",
             "Check-in, colazione e tassa di soggiorno.",
             "Заселение, завтрак и туристический сбор.",
             "hotel", 2, [
        step("al-1", "build",
             prompt_ru="Скажи, что у тебя бронь.",
             prompt_it="Dì che hai una prenotazione.",
             target_it=side("Ho una prenotazione."),
             target_ru=side("У меня бронь."),
             distractors={"it": ["camera", "notte"]}),
        step("al-2", "comprehension",
             npc_it=side("Mi lascia un documento, per favore?"),
             npc_ru=side("Оставьте документ, пожалуйста."),
             prompt_ru="Что просит администратор?",
             prompt_it="Che cosa ti chiede?",
             options_ru=["Документ", "Оплату наличными", "Подпись на договоре", "Номер рейса"],
             correct=0),
        step("al-3", "info",
             prompt_ru="В Италии отель обязан переписать данные документа. Туристический сбор часто платят отдельно.",
             prompt_it="La tassa di soggiorno si paga spesso a parte."),
        step("al-4", "build",
             prompt_ru="Спроси, во сколько завтрак.",
             prompt_it="Chiedi a che ora è la colazione.",
             target_it=side("A che ora è la colazione?"),
             target_ru=side("Во сколько завтрак?"),
             distractors={"it": ["dove", "quanto"]}),
        step("al-5", "choice",
             npc_it=side("Dalle sette alle dieci. La tassa di soggiorno è due euro a notte."),
             npc_ru=side("С семи до десяти. Туристический сбор — два евро за ночь."),
             prompt_ru="Что ещё надо оплатить?",
             prompt_it="Che cosa devi pagare in più?",
             options_it=["La tassa di soggiorno.", "La colazione.",
                         "Il parcheggio.", "Niente."],
             correct=0),
        step("al-6", "pronounce",
             prompt_ru="Произнеси вслух.", prompt_it="Dillo ad alta voce.",
             target_it=side("Il wifi ha una password?"),
             target_ru=side("У вайфая есть пароль?")),
    ]),

    scenario("it-indicazioni", "Chiedere la strada", "Спросить дорогу", "location",
             "Orientarsi in un centro storico.",
             "Сориентироваться в историческом центре.",
             "directions", 2, [
        step("in-1", "build",
             prompt_ru="Вежливо привлеки внимание и спроси, где вокзал.",
             prompt_it="Chiedi dov'è la stazione.",
             target_it=side("Scusi, dov'è la stazione?"),
             target_ru=side("Извините, где вокзал?"),
             distractors={"it": ["quando", "quanto"]}),
        step("in-2", "comprehension",
             npc_it=side("Sempre dritto, poi la seconda a destra."),
             npc_ru=side("Всё время прямо, потом вторая направо."),
             prompt_ru="Куда идти?", prompt_it="Dove devi andare?",
             options_ru=["Прямо, потом вторая направо", "Первая налево",
                         "Назад к площади", "На автобусе"],
             correct=0),
        step("in-3", "choice",
             prompt_ru="Ты не понял. Попроси повторить помедленнее.",
             prompt_it="Non hai capito. Chiedi di ripetere.",
             options_it=["Può ripetere più lentamente?", "Quanto costa?",
                         "Dov'è il bagno?", "Va bene, grazie."],
             correct=0),
        step("in-4", "build",
             prompt_ru="Спроси, далеко ли пешком.",
             prompt_it="Chiedi se è lontano a piedi.",
             target_it=side("È lontano a piedi?"),
             target_ru=side("Далеко пешком?"),
             distractors={"it": ["treno"]}),
        step("in-5", "pronounce",
             prompt_ru="Поблагодари.", prompt_it="Ringrazia.",
             target_it=side("Grazie mille!"),
             target_ru=side("Большое спасибо!")),
    ]),

    scenario("it-conoscere", "Fare conoscenza", "Знакомство", "person.2",
             "Presentarsi e reggere due minuti di conversazione.",
             "Представиться и продержаться две минуты в разговоре.",
             "conversation", 1, [
        step("co-1", "comprehension",
             npc_it=side("Ciao! Come ti chiami?"),
             npc_ru=side("Привет! Как тебя зовут?"),
             prompt_ru="О чём спрашивают?", prompt_it="Che cosa ti chiede?",
             options_ru=["Как тебя зовут", "Откуда ты", "Сколько тебе лет", "Где ты живёшь"],
             correct=0),
        step("co-2", "build",
             prompt_ru="Представься: «Меня зовут Анна».",
             prompt_it="Presentati.",
             target_it=side("Mi chiamo Anna."),
             target_ru=side("Меня зовут Анна."),
             distractors={"it": ["sono", "tu"]}),
        step("co-3", "choice",
             npc_it=side("Di dove sei?"),
             npc_ru=side("Откуда ты?"),
             prompt_ru="Скажи, что ты из России.",
             prompt_it="Dì che vieni dalla Russia.",
             options_it=["Vengo dalla Russia.", "Vado in Russia.",
                         "Sono italiano.", "Abito qui."],
             correct=0),
        step("co-4", "build",
             prompt_ru="Скажи, что учишь итальянский.",
             prompt_it="Dì che studi italiano.",
             target_it=side("Studio italiano."),
             target_ru=side("Я учу итальянский."),
             distractors={"it": ["russo", "parlo"]}),
        step("co-5", "pronounce",
             prompt_ru="Произнеси вслух.", prompt_it="Dillo ad alta voce.",
             target_it=side("Piacere di conoscerti."),
             target_ru=side("Приятно познакомиться.")),
    ]),

    scenario("it-autobus", "L'autobus urbano", "Городской автобус", "bus",
             "Il biglietto si compra prima di salire.",
             "Билет покупают до посадки.",
             "city", 2, [
        step("au-1", "info",
             prompt_ru="Билет на автобус покупают в табачном киоске (tabaccheria), а не у водителя.",
             prompt_it="Il biglietto si compra in tabaccheria."),
        step("au-2", "build",
             prompt_ru="Попроси два билета на автобус.",
             prompt_it="Chiedi due biglietti dell'autobus.",
             target_it=side("Due biglietti dell'autobus, per favore."),
             target_ru=side("Два билета на автобус, пожалуйста."),
             distractors={"it": ["treno", "tre"]}),
        step("au-3", "comprehension",
             npc_it=side("Valgono novanta minuti dalla convalida."),
             npc_ru=side("Действуют девяносто минут с момента компостирования."),
             prompt_ru="Сколько действует билет?",
             prompt_it="Quanto vale il biglietto?",
             options_ru=["90 минут с компостирования", "Весь день",
                         "Одну поездку без времени", "До полуночи"],
             correct=0),
        step("au-4", "choice",
             prompt_ru="Спроси, идёт ли этот автобус в центр.",
             prompt_it="Chiedi se va in centro.",
             options_it=["Questo autobus va in centro?", "Quanto costa il taxi?",
                         "Dov'è la stazione?", "A che ora chiude?"],
             correct=0),
        step("au-5", "pronounce",
             prompt_ru="Произнеси вслух.", prompt_it="Dillo ad alta voce.",
             target_it=side("Scendo alla prossima."),
             target_ru=side("Я выхожу на следующей.")),
    ]),

    scenario("it-emergenza", "Un piccolo problema", "Небольшая проблема", "exclamationmark.triangle",
             "Perdere qualcosa e chiedere aiuto.",
             "Потерять вещь и попросить помощи.",
             "emergency", 3, [
        step("em-1", "build",
             prompt_ru="Скажи, что потерял телефон.",
             prompt_it="Dì che hai perso il telefono.",
             target_it=side("Ho perso il telefono."),
             target_ru=side("Я потерял телефон."),
             distractors={"it": ["borsa", "trovato"]}),
        step("em-2", "comprehension",
             npc_it=side("Dove l'ha visto l'ultima volta?"),
             npc_ru=side("Где вы его видели в последний раз?"),
             prompt_ru="О чём спрашивают?", prompt_it="Che cosa ti chiede?",
             options_ru=["Где ты видел его в последний раз", "Какой у него цвет",
                         "Сколько он стоил", "Есть ли чек"],
             correct=0),
        step("em-3", "choice",
             prompt_ru="Ответь: в автобусе.", prompt_it="Rispondi: sull'autobus.",
             options_it=["Sull'autobus.", "In albergo.", "Non lo so.", "A casa."],
             correct=0),
        step("em-4", "build",
             prompt_ru="Спроси, можно ли позвонить.",
             prompt_it="Chiedi se puoi fare una telefonata.",
             target_it=side("Posso fare una telefonata?"),
             target_ru=side("Можно позвонить?"),
             distractors={"it": ["dove"]}),
        step("em-5", "pronounce",
             prompt_ru="Произнеси вслух.", prompt_it="Dillo ad alta voce.",
             target_it=side("Mi può aiutare, per favore?"),
             target_ru=side("Вы можете мне помочь?")),
    ]),
]


def write(name, data):
    path = os.path.join(OUT, name)
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(data, handle, ensure_ascii=False, indent=1)
        handle.write("\n")
    print(f"{name}: {len(data)} entries")


existing = json.load(open(os.path.join(OUT, "scenarios.json"), encoding="utf-8"))
russia = [s for s in existing if s["direction"] == "it-ru"]
write("scenarios.json", russia + ITALY)
write("patterns.json", PATTERNS)
write("idioms.json", IDIOMS)
write("culture.json", CULTURE)
write("tips.json", TIPS)
